export const MAJOR_TAGS = [
  "Computer Engineering",
  "Visual Design",
  "Economics",
  "Business Administration",
  "Psychology",
  "Social Studies",
  "Mathematics",
  "Statistics",
  "Physics",
  "Chemistry",
  "Biology",
  "Earch Sciences",
  "Law",
  "Medicine",
  "Pharmacy",
];

export const SKILL_TAGS = [
  "Frontend",
  "Backend",
  "Software Engineering",
  "Deep Learning",
  "Machine Learning",
  "DevOps",
  "MLOps",
  "Financial Engineering",
  "Consulting",
  "Human Resources",
  "Entrepreneurship",
  "Blockchain",
  "Accounting",
];
