export const QUALITY_TAGS = [
  "Sincere",
  "Honest",
  "Understanding",
  "Loyal",
  "Truthful",
  "Trustworthy",
  "Intelligent",
  "Dependable",
  "Open-Minded",
  "Thoughtful",
  "Wise",
  "Considerate",
  "Good-Natured",
  "Reliable",
  "Mature",
  "Warm",
  "Earnest",
  "Kind",
  "Friendly",
  "Kind-Hearted",
  "Happy",
  "Clean",
  "Interesting",
  "Unselfish",
  "Good-Humored",
  "Honorable",
  "Humorous",
  "Responsible",
  "Cheerful",
  "Trustful",
  "Warm-Hearted",
  "Broad-Minded",
  "Gentle",
  "Well-Spoken",
  "Educated",
  "Reasonable",
  "Companionable",
  "Likable",
  "Trusting",
  "Clever",
  "Pleasant",
  "Courteous",
  "Quick-Witted",
  "Tactful",
  "Helpful",
  "Appreciative",
  "Imaginative",
  "Outstanding",
  "Self-Disciplined",
  "Brilliant",
  "Enthusiastic",
  "Level-Headed",
  "Polite",
  "Original",
  "Smart",
  "Forgiving",
  "Sharp-Witted",
  "Well-Read",
  "Ambitious",
  "Bright",
  "Respectful",
  "Efficient",
  "Good-Tempered",
  "Grateful",
  "Conscientious",
  "Resourceful",
  "Alert",
  "Good",
  "Witty",
  "Clear-Headed",
  "Kindly",
  "Admirable",
  "Patient",
  "Talented",
  "Perceptive",
  "Spirited",
  "Sportsmanlike",
  "Well-Mannered",
  "Cooperative",
  "Ethical",
  "Intellectual",
  "Versatile",
  "Capable",
  "Courageous",
  "Constructive",
  "Productive",
  "Progressive",
  "Individualistic",
  "Observant",
  "Ingenious",
  "Lively",
  "Neat",
  "Punctual",
  "Logical",
  "Prompt",
  "Accurate",
  "Sensible",
  "Creative",
  "Self-Reliant",
  "Tolerant",
];

export const MAJOR_TAGS = [
  "Computer Engineering",
  "Visual Design",
  "Economics",
  "Business Administration",
  "Psychology",
  "Social Studies",
  "Mathematics",
  "Statistics",
  "Physics",
  "Chemistry",
  "Biology",
  "Earch Sciences",
  "Law",
  "Medicine",
  "Pharmacy",
];

export const DEGREE_TAGS = ["undergraduate", "graduate", "BA", "MA", "PhD"];

export const LANGUAGE_TAGS = [
  "English",
  "Korean",
  "Japanese",
  "Chinese",
  "Spanish",
  "French",
  "Italian",
];

export const SKILL_TAGS = [
  "Frontend",
  "Backend",
  "Software Engineering",
  "Deep Learning",
  "Machine Learning",
  "DevOps",
  "MLOps",
  "Financial Engineering",
  "Consulting",
  "Human Resources",
  "Entrepreneurship",
  "Blockchain",
  "Accounting",
];
