"""
url module for linklink app
"""

from django.urls import path
from linklink import views

urlpatterns = [
    path(
        'csrf_token/',
        views.csrf_token,
        name='csrf_token'
    ),
    path(
        'auth/signup/',
        views.signup,
        name='signup'
    ),
    path(
        'auth/signin/',
        views.signin,
        name='signin'
    ),
    path(
        'auth/signout/',
        views.signout,
        name='signout'
    ),
    path(
        'auth/verify/<str:token>/',
        views.verify,
        name='verify'
    ),
    path(
        'user/friend/',
        views.friend,
        name='friend'
    ),
    path(
        'user/friendRequestToken/',
        views.friend_request_token,
        name='friend_request_token'
    ),
    path(
        'profile/',
        views.my_profile,
        name='my_profile'
    ),
    path(
        'profile/<int:user_id>/',
        views.profile,
        name='profile'
    ),
    path(
        'profile/uploadImage/',
        views.upload_image,
        name='upload_image'
    ),
    path(
        'friendRequest/',
        views.friend_request,
        name='friend_request'
    ),
    path(
        'friendRequest/<int:friend_request_id>/',
        views.friend_request_respond,
        name='friend_request_respond'
    ),
]
