# Generated by Django 4.1 on 2022-10-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linklink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linklinkuser',
            name='oneChon',
            field=models.ManyToManyField(blank=True, to='linklink.friendrequest'),
        ),
    ]
