# Generated by Django 4.1 on 2022-11-03 05:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('linklink', '0002_alter_linklinkuser_onechon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verification',
            old_name='expiredAt',
            new_name='expiresAt',
        ),
        migrations.RemoveField(
            model_name='linklinkuser',
            name='nickname',
        ),
        migrations.AlterField(
            model_name='linklinkuser',
            name='emailValidated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='linklinkuser',
            name='friendRequestToken',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='verification',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
