# Generated by Django 4.1 on 2022-11-03 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linklink', '0003_rename_expiredat_verification_expiresat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verification',
            old_name='user',
            new_name='linklinkuser',
        ),
    ]
