# Generated by Django 4.1 on 2022-11-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linklink', '0006_rename_imageurl_linklinkuser_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linklinkuser',
            name='imgUrl',
            field=models.CharField(default='https://catimage.com', max_length=400),
        ),
    ]
