# Generated by Django 4.1 on 2022-11-08 14:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('linklink', '0008_alter_verification_linklinkuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linklinkuser',
            name='friendRequestToken',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
