# Generated by Django 4.1 on 2022-11-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linklink', '0011_linklinkuser_email_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linklinkuser',
            name='email_unique',
            field=models.EmailField(default='invalidemail@snu.ac.kr', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
