# Generated by Django 4.1 on 2022-11-11 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linklink', '0012_alter_linklinkuser_email_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='qualityTags',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skillTags',
        ),
    ]
