# Generated by Django 4.1 on 2022-11-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linklink', '0013_remove_profile_qualitytags_remove_profile_skilltags'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qualityTags',
            field=models.ManyToManyField(to='linklink.qualitytag'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skillTags',
            field=models.ManyToManyField(to='linklink.skilltag'),
        ),
    ]
