# Generated by Django 4.1 on 2022-11-11 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linklink', '0014_profile_qualitytags_profile_skilltags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='chatLogs',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='users',
        ),
        migrations.DeleteModel(
            name='ChatLog',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
