# Generated by Django 4.1 on 2022-11-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linklink', '0016_remove_linklinkuser_imgurl_profile_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imgUrl',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
