# Generated by Django 4.1 on 2022-11-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linklink', '0017_alter_profile_imgurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='unique_request_id',
            field=models.CharField(default='1-2', max_length=100),
            preserve_default=False,
        ),
    ]
