# Generated by Django 4.1 on 2022-11-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linklink', '0018_friendrequest_unique_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='unique_request_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
