# Generated by Django 4.1 on 2022-11-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linklink', '0019_alter_friendrequest_unique_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='unique_request_id',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
