# Generated by Django 4.1 on 2022-12-03 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linklink', '0020_alter_friendrequest_unique_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitytag',
            name='name',
            field=models.CharField(choices=[('성실한', '성실한'), ('정직한', '정직한'), ('이해심이 깊은', '이해심이 깊은'), ('논리적인', '논리적인'), ('유쾌한', '유쾌한'), ('쾌활한', '쾌활한'), ('분석적인', '분석적인'), ('배려심이 깊은', '배려심이 깊은'), ('유머러스한', '유머러스한'), ('유능한', '유능한'), ('믿음직한', '믿음직한'), ('리더십 있는', '리더십 있는'), ('열려 있는', '열려 있는'), ('신중한', '신중한'), ('따뜻한', '따뜻한'), ('열정적인', '열정적인'), ('흥미로운', '흥미로운'), ('책임감 있는', '책임감 있는'), ('모험적인', '모험적인'), ('한결 같은', '한결 같은'), ('감각적인', '감각적인'), ('밝은', '밝은'), ('솔선수범 하는', '솔선수범 하는'), ('효율적인', '효율적인'), ('꼼꼼한', '꼼꼼한')], max_length=30),
        ),
        migrations.CreateModel(
            name='QualityTagRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('성실한', '성실한'), ('정직한', '정직한'), ('이해심이 깊은', '이해심이 깊은'), ('논리적인', '논리적인'), ('유쾌한', '유쾌한'), ('쾌활한', '쾌활한'), ('분석적인', '분석적인'), ('배려심이 깊은', '배려심이 깊은'), ('유머러스한', '유머러스한'), ('유능한', '유능한'), ('믿음직한', '믿음직한'), ('리더십 있는', '리더십 있는'), ('열려 있는', '열려 있는'), ('신중한', '신중한'), ('따뜻한', '따뜻한'), ('열정적인', '열정적인'), ('흥미로운', '흥미로운'), ('책임감 있는', '책임감 있는'), ('모험적인', '모험적인'), ('한결 같은', '한결 같은'), ('감각적인', '감각적인'), ('밝은', '밝은'), ('솔선수범 하는', '솔선수범 하는'), ('효율적인', '효율적인'), ('꼼꼼한', '꼼꼼한')], max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('unique_request_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('getterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='getterIdQualityTagRequest', to='linklink.linklinkuser')),
                ('senderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senderIdQualityTagRequest', to='linklink.linklinkuser')),
            ],
        ),
    ]
