# Generated by Django 4.1 on 2022-12-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linklink", "0021_chatroom_message"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="timestamp",
            new_name="timeStamp",
        ),
        migrations.RemoveField(
            model_name="chatroom",
            name="user1",
        ),
        migrations.RemoveField(
            model_name="chatroom",
            name="user2",
        ),
        migrations.AddField(
            model_name="chatroom",
            name="online",
            field=models.ManyToManyField(blank=True, to="linklink.linklinkuser"),
        ),
        migrations.AddField(
            model_name="message",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
