# Generated by Django 4.1 on 2022-12-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linklink', '0024_alter_qualitytag_name_qualitytagrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='qualityTags',
        ),
    ]
